-- collegepapers.in: Legacy Database Backup
-- Generated manually on: 2026-07-14

-- --------------------------------------------------------
-- Table Structure: institutions
-- --------------------------------------------------------
-- CREATE TABLE public.institutions (
--     id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--     name text NOT NULL,
--     type text NOT NULL,
--     parent_id uuid REFERENCES public.institutions(id) ON DELETE CASCADE,
--     created_at timestamptz DEFAULT now()
-- );

-- Table Data: institutions
-- [
--   {"id":"11111111-1111-1111-1111-111111111111","name":"Pandit Ravishankar Shukla University (PRSU)","type":"university","parent_id":null,"created_at":"2026-06-17 11:07:43.463817+00"},
--   {"id":"22222222-2222-2222-2222-222222222222","name":"Swami Aatmanand College, Atari","type":"college","parent_id":"11111111-1111-1111-1111-111111111111","created_at":"2026-06-17 11:07:43.463817+00"},
--   {"id":"33333333-3333-3333-3333-333333333333","name":"Government V.Y.T. PG Autonomous College","type":"autonomous_college","parent_id":null,"created_at":"2026-06-17 11:07:43.463817+00"}
-- ]

-- --------------------------------------------------------
-- Table Structure: papers
-- --------------------------------------------------------
-- CREATE TABLE public.papers (
--     id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--     institution_id uuid REFERENCES public.institutions(id) ON DELETE RESTRICT,
--     course text NOT NULL,
--     semester integer NOT NULL,
--     subject text NOT NULL,
--     exam_type text NOT NULL,
--     pdf_path text NOT NULL,
--     is_premium boolean DEFAULT false,
--     created_at timestamptz DEFAULT now()
-- );

-- Table Data: papers
-- [
--   {"id":"da698f77-7684-4efe-a1c5-d44a79efd2ee","institution_id":"11111111-1111-1111-1111-111111111111","course":"BCA","semester":1,"subject":"Discrete Mathematics","exam_type":"Semester","pdf_path":"prsu/atmanand/bca/sem1/sem_main/2025/bca-1-sem-discrete-mathematics-j-2205-jan-2026.pdf","is_premium":false,"created_at":"2026-06-27 16:55:47.941096+00"}
-- ]

-- --------------------------------------------------------
-- Table Structure: papers_metadata
-- --------------------------------------------------------
-- CREATE TABLE public.papers_metadata (
--     id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     created_at timestamptz DEFAULT now(),
--     title text,
--     file_url text,
--     university text,
--     college text,
--     course text,
--     semester text,
--     subject text,
--     uni_image_url text,
--     col_image_url text,
--     year text
-- );

-- Table Data: papers_metadata
-- [
--   {"id":3,"created_at":"2026-07-06 09:24:39.512237+00","title":"Chemistry","file_url":"science clg/bsc/sem 4/2026/CB-404_Digital_OCR_Draft.pdf","university":"Government Nagarjuna Science College","college":null,"course":"BSC","semester":"4","subject":"Chemistry","uni_image_url":"https://osdqszlyyhetdnlargrn.supabase.co/storage/v1/object/public/institutes%20_images/prsu/nagarjun_uni_img.jpg","col_image_url":null,"year":"2026"},
--   {"id":2,"created_at":"2026-07-03 13:22:06.331466+00","title":"Data Structure","file_url":"prsu/atmanand atari/bca/sem 2/2025/bca-2-sem-data-structure-i-2253-june-2025.pdf","university":"Pt. Ravishankar Shukla University","college":"Swami Atmanand Government English Medium Model Colleges (SAGEMMC)","course":"BCA","semester":"2","subject":"Data Structure","uni_image_url":"https://osdqszlyyhetdnlargrn.supabase.co/storage/v1/object/public/institutes%20_images/prsu/prsu_uni_img.jpeg","col_image_url":"https://osdqszlyyhetdnlargrn.supabase.co/storage/v1/object/public/institutes%20_images/prsu/atmanand_clg_img.jpeg","year":"2025"},
--   {"id":1,"created_at":"2026-06-30 10:29:05.151929+00","title":"Discrete Mathmatic","file_url":"prsu/atmanand atari/bca/sem 1/2025/bca-1-sem-discrete-mathematics-j-2205-jan-2026.pdf","university":"Pt. Ravishankar Shukla University","college":"Swami Atmanand Government English Medium Model Colleges (SAGEMMC)","course":"BCA","semester":"1","subject":"Discrete Mathmatics","uni_image_url":"https://osdqszlyyhetdnlargrn.supabase.co/storage/v1/object/public/institutes%20_images/prsu/prsu_uni_img.jpeg","col_image_url":"https://osdqszlyyhetdnlargrn.supabase.co/storage/v1/object/public/institutes%20_images/prsu/atmanand_clg_img.jpeg","year":"2025"}
-- ]

-- --------------------------------------------------------
-- Table Structure: download_logs, funnel_stats, verifications (All 0 rows)
-- --------------------------------------------------------
